travis:
  secure:
    BINSTAR_TOKEN: M8ZFg0Hs17aLK+0cnvyf4J/SyDUyEddZHsC+Lij+4d82itATWtZjTpYIkPuVd9D7P1dRpaSv97VO3BnsDUooylJJxj931rancdL4iO2fG2d34j6WP63/7ElNQqGGbM9zyHtsX8Kqe+ikugdJJsEOT5BgiO5aiUe8SPFj+cIVu0dPofDp7frIiBrmsFafLLUZ513d1qY1XOywXIPws8xq6DgVUfmkojexYrLWYTCGUlue7gnROKiCssqO1AnvwrJS3/pJ6vKY28BuZQHfnPW+Vfs35PkdWPNvk2AR0Oar0u6b2PDJZQmG9/GOyOW9P11+QrXO1m6C8ywtOr6DYX9UQf8ieuNukC7QXWqWIuODl9aPauVkIEU5fZG4Qa70DhWZk4m2gx/80TSyu/dcK15CxqT4ysNpMxfX2whxJFcUpcW5Mxa0DA515tC0EgKEFmaqdZS+bAe7GlkNVIdJkGjYV/e94uFwG2j91gxNEv4GCSZTduUj6JXryGiXZkRbIjzFUQn64agDrufiVg+S8dI0l0pZ3uks3Jph7n7ESTiTbMcsBijM5r/tmdyDsmHj3ua9bnveUh/N9mrNLULxOfKSHUNQ5CnB9E8Z3Ej4UE0tYBWPLlCqDJ2qirZ1E+B14qVJoME9z5Fx96ipVxCI84aBomChQkl9ixHz/RZkeVQv53c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
